topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  ad_master_2client: &ad_master_2client
    name: ad_master_2client
    cpu: 4
    memory: 10596

jobs:
  fedora-latest/build:
    requires: []
    priority: 150
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-latest
          name: freeipa/ci-master-f44
          version: 0.0.1
        timeout: 1800
        topology: *build

  fedora-latest/test_smb:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_smb.py
        template: *ci-master-latest
        timeout: 7200
        topology: *ad_master_2client
