#
# Template for temporary test commit
#
# $ ln -sf ipatests/prci_definitions/temp_commit.yaml .freeipa-pr-ci.yaml
#

topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_3client: &master_3client
    name: master_3client
    cpu: 5
    memory: 10150
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10150
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900
  ad_master_2client: &ad_master_2client
    name: ad_master_2client
    cpu: 4
    memory: 12000
  ad_master: &ad_master
    name: ad_master
    cpu: 4
    memory: 12000
  adroot_adchild_adtree_master_1client: &adroot_adchild_adtree_master_1client
    name: adroot_adchild_adtree_master_1client
    cpu: 8
    memory: 14500

jobs:
  testing-fedora/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &testing-master-latest
          name: freeipa/testing-master-f34
          version: 0.0.1
        timeout: 1800
        topology: *build

  testing-fedora/test_smb:
    requires: [testing-fedora/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{testing-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_smb.py
        template: *testing-master-latest
        timeout: 7200
        topology: *ad_master_2client

